### ISSUE TITLE
open device error

### ISSUE THREAD

**Issue by audiodock81** [Andy-jg/RaspberryCanalyst-2#1]
I am new to linux and I am trying to install Canalyst 2 on ubuntu 18.04 64bit. I have fallowed the installation guide for this device but am getting device error code. The read me file said I need to modify the test sample c code but dont know why? This is what I have done so far.

chris@Dell7412:~$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 7.4.0-1ubuntu1~18.04' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04) 
chris@Dell7412:~$ lsusb
Bus 002 Device 004: ID 0a5c:5800 Broadcom Corp. BCM5880 Secure Applications Processor
Bus 002 Device 003: ID 04d8:0053 Microchip Technology, Inc. 
Bus 002 Device 002: ID 8087:0024 Intel Corp. Integrated Rate Matching Hub
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 001 Device 004: ID 1bcf:2802 Sunplus Innovation Technology Inc. 
Bus 001 Device 003: ID 413c:8187 Dell Computer Corp. DW375 Bluetooth Module
Bus 001 Device 002: ID 8087:0024 Intel Corp. Integrated Rate Matching Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
chris@Dell7412:~$ ls
chrysler.log  Documents  examples.desktop  Music     Public  Templates
Desktop       Downloads  mcba_usb          Pictures  snap    Videos
chris@Dell7412:~$ cd \Desktop
chris@Dell7412:~/Desktop$ ls controlcan
controlcan.h  hello_cpp  libcontrolcan.so  main.cpp  Makefile
chris@Dell7412:~/Desktop$ cd \controlcan
chris@Dell7412:~/Desktop/controlcan$ ls
controlcan.h  hello_cpp  libcontrolcan.so  main.cpp  Makefile
chris@Dell7412:~/Desktop/controlcan$ rm hello_cpp
chris@Dell7412:~/Desktop/controlcan$ ls
controlcan.h  libcontrolcan.so  main.cpp  Makefile
chris@Dell7412:~/Desktop/controlcan$ gedit main.cpp
chris@Dell7412:~/Desktop/controlcan$ ls
controlcan.h  libcontrolcan.so  main.cpp  Makefile
chris@Dell7412:~/Desktop/controlcan$ make clean && make
rm -f *.o hello
#gcc -o hello -L. -lcontrolcan -lpthread -lusb main.c
#arm-none-linux-gnueabi-gcc -o hello -L. -L /home/caidunqing/controlcan -lcontrolcan -lpthread main.c
g++ -o hello_cpp main.cpp /home/chris/Desktop/controlcan/libcontrolcan.so  -lpthread 
chris@Dell7412:~/Desktop/controlcan$ sudo ./hello_cpp
[sudo] password for chris: 
>>this is hello !
>>open deivce error!
chris@Dell7412:~/Desktop/controlcan$ sudo ./hello_cpp
>>this is hello !
>>open deivce error!
chris@Dell7412:~/Desktop/controlcan$ sudo ./hello_cpp
>>this is hello !
>>open deivce error!
chris@Dell7412:~/Desktop/controlcan$

**Comment by Andy-jg** [comment]
open device error
You need to communicate with the supplier(where by the Canalyst-2 )and recompile .so file to use on your computer. My computer is raspberry.
